ADDR = (SERVER, PORT) = ("127.0.0.1", "65534")
SA = ";;SELAMIN?ALEYKUM?KARDESIM"
AS = ";;ALEYKUM?SELAM?KARDESIM"
DISCONNECT = ";;END"
START = ";;START"
RECV_ = ";;RECV"
FORMAT = "utf-8"
HEADER = 16

receiver = 0
sender = 1
